name: EMGATA API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'EMGATA.API/**'
      - 'EMGATA.Tests/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'EMGATA.API/**'
      - 'EMGATA.Tests/**'
      - '.github/workflows/**'

env:
  DOTNET_VERSION: '8.0.x'
  WORKING_DIRECTORY: 'EMGATA.API'
  TEST_DIRECTORY: 'EMGATA.Tests'
  AZURE_WEBAPP_NAME: 'atetheone-emgata-api'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ env.TEST_DIRECTORY }}
    
    - name: Publish
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.WORKING_DIRECTORY }}/publish

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: webapp
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .