name: EMGATA.API Continuous Integration and Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: "8.0.x"
  API_PROJECT_PATH: "./EMGATA.API"
  TEST_PROJECT_PATH: "./EMGATA.Tests"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restauration distincte pour l'API et les Tests
      - name: Restore API Solution
        run: |
          cd ${{ env.API_PROJECT_PATH }}
          dotnet restore

      - name: Restore Test Project
        run: |
          cd ${{ env.TEST_PROJECT_PATH }}
          dotnet restore

      # Build de l'API
      - name: Build API
        run: |
          cd ${{ env.API_PROJECT_PATH }}
          dotnet build --configuration Release --no-restore

      # Build des Tests
      - name: Build Tests
        run: |
          cd ${{ env.TEST_PROJECT_PATH }}
          dotnet build --configuration Release --no-restore

      # Exécution des Tests
      - name: Run Tests
        run: |
          cd ${{ env.TEST_PROJECT_PATH }}
          dotnet test --configuration Release --no-build --verbosity normal

      # Publication de l'API
      - name: Publish API
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${{ env.API_PROJECT_PATH }}
          dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}/publish
          retention-days: 5

  deploy-to-azure:
    name: Deploy to Azure App Service
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: atetheone-emgata-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish